### ISSUE TITLE
How to visualize the intersection?

### ISSUE THREAD

**Issue by dineshadepu** [catenda/intersection-wasm#1]
Hi,

I am new to node js. I am working on a similar project but in a different direction. I need to check If two polyhedron intersect, so I think might help me some way. 

I followed the instructions and able to build it. But I don't see any figure of two triangles intersecting. Can you help me with the visulaizing it? Like the image on your twitter post. 

Thanks.

**Comment by barabadzhi** [comment]
Hey @dineshadepu

Thanks for your interest in `intersection-wasm` package.

Polyhedron or any other figure can be easily represented as a collection of [meshes](https://en.wikipedia.org/wiki/Polygon_mesh), so you can directly use `intersection-wasm`'s  `meshMeshIsect` function to detect intersections.

We do not provide any drawing capabilities however. This is a pure algorithm library.
In order to visualize meshes I would advice you to look into [threejs](https://threejs.org/docs/index.html#manual/en/introduction/Creating-a-scene), especially [EdgesGeometry](https://threejs.org/docs/#api/en/geometries/EdgesGeometry) and alike.

Hope I was helpful enough.
I'm closing this.

Happy coding! :slightly_smiling_face:
